application:
    title: gateway-server
    version: 0.0.1
    log:
        path: /tmp/logs/springcloudexamples

spring:
    application:
        name: gateway-server
    profiles:
        active: dev
    cloud:
        config:
            uri: http://localhost:8888/
    config:
        import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"

springdoc:
    version: '@springdoc.version@'
    swagger-ui:
        use-root-path: true
