spring:
    application:
        name: gateway-server
    profiles:
        active: dev
    cloud:
        config:
            uri: http://localhost:8888/

    config:
        import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"
