version: '3.7'

services:
    zipkin:
        image: openzipkin/zipkin:latest
        container_name: zipkin
        hostname: zipkin
        restart: unless-stopped
        ports:
            - "9411:9411"
