version: '3.7'

services:
    zipkin:
        image: openzipkin/zipkin:latest
        container_name: zipkin
        hostname: zipkin
        restart: unless-stopped
        ports:
            - "9411:9411"
    postgreskc:
        image: postgres:alpine
        container_name: postgreskc
        hostname: postgreskc
        restart: unless-stopped
#        ports:
#            - "5432:5432"
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
            POSTGRES_DB: keycloak
            POSTGRES_HOST: postgres
        volumes:
            - postgreskc_data:/var/lib/postgresql/data
    keycloak:
        image: quay.io/keycloak/keycloak:legacy
        container_name: keycloak
        hostname: keycloak
        restart: unless-stopped
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgreskc
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
            - "8880:8080"
        depends_on:
            - postgreskc
#    gogsdb:
#        image: tareqmy/postgres:latest
#        container_name: gogsdb
#        hostname: gogsdb
#        restart: unless-stopped
#        stdin_open: true
#        tty: true
#        environment:
#            - "POSTGRES_USER=gogs"
#            - "POSTGRES_PASSWORD=gogs"
#            - "POSTGRES_DB=gogs"
#        volumes:
#            - "gogsdb-data:/var/lib/postgresql/data"
#    gogs:
#        image: gogs/gogs:latest
#        container_name: gogs
#        hostname: gogs
#        restart: unless-stopped
#        stdin_open: true
#        tty: true
#        ports:
#            - "10022:22"
#            - "3000:3000"
#        links:
#            - gogsdb
#        environment:
#            - "RUN_CROND=true"
#        volumes:
#            - "gogs-data:/data"
#        depends_on:
#            - gogsdb

volumes:
#    gogsdb-data:
#        driver: local
#    gogs-data:
#        driver: local
    postgreskc_data:
        driver: local
