version: '3.7'

services:
    zipkin:
        image: openzipkin/zipkin:latest
        container_name: zipkin
        hostname: zipkin
        restart: unless-stopped
        ports:
            - "9411:9411"
    postgreskc:
        image: postgres:alpine
        container_name: postgreskc
        hostname: postgreskc
        restart: unless-stopped
#        ports:
#            - "5432:5432"
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
            POSTGRES_DB: keycloak
            POSTGRES_HOST: postgres
        volumes:
            - postgreskc_data:/var/lib/postgresql/data
    keycloak:
        image: quay.io/keycloak/keycloak:legacy
        container_name: keycloak
        hostname: keycloak
        restart: unless-stopped
        environment:
            DB_VENDOR: postgres
            DB_ADDR: postgreskc
            DB_PORT: 5432
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
            # KEYCLOAK_LOGLEVEL: DEBUG
            JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
            JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
        depends_on:
            - postgreskc
        labels:
            traefik.enable: true
            traefik.port: 8080
            traefik.protocol: http
            traefik.frontend.rule: Host:localhost
            traefik.frontend.passHostHeader: true
            # traefik.backend.loadbalancer.stickiness: true
    traefik:
        image: library/traefik:alpine
        container_name: traefik
        hostname: traefik
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: >
            --logLevel=ERROR
            --api.dashboard
            --docker
            --entrypoints="Name:http Address::80"
            --defaultentrypoints="http"
        ports:
            - "8880:80"
            - "8980:8080"
#    gogsdb:
#        image: tareqmy/postgres:latest
#        container_name: gogsdb
#        hostname: gogsdb
#        restart: unless-stopped
#        stdin_open: true
#        tty: true
#        environment:
#            - "POSTGRES_USER=gogs"
#            - "POSTGRES_PASSWORD=gogs"
#            - "POSTGRES_DB=gogs"
#        volumes:
#            - "gogsdb-data:/var/lib/postgresql/data"
#    gogs:
#        image: gogs/gogs:latest
#        container_name: gogs
#        hostname: gogs
#        restart: unless-stopped
#        stdin_open: true
#        tty: true
#        ports:
#            - "10022:22"
#            - "3000:3000"
#        links:
#            - gogsdb
#        environment:
#            - "RUN_CROND=true"
#        volumes:
#            - "gogs-data:/data"
#        depends_on:
#            - gogsdb

volumes:
#    gogsdb-data:
#        driver: local
#    gogs-data:
#        driver: local
    postgreskc_data:
        driver: local
