application:
    title: organization-service
    version: 0.0.1
    log:
        path: /tmp/logs/springcloudexamples

spring:
    application:
        name: organization-service
    profiles:
        active: dev
    cloud:
        config:
            uri: http://localhost:8888/

    config:
        import: "optional:configserver:${CONFIG_SERVER:http://localhost:8888}"

    devtools:
        livereload:
            port: 35731

    logstash:
        server: ${LOGSTASH_SERVER:localhost}
        port: ${LOGSTASH_PORT:5000}

springdoc:
    version: '@springdoc.version@'
    show-actuator: false
