server:
    port: 9090

spring:
    security:
        user:
            name: admin
            password: 53cr3t

eureka:
    client:
        register-with-eureka: false
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Logging
logging:
    level:
        root: INFO
        #        web: DEBUG
        com.tareqmy.adminserver: DEBUG
