eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
    port: 8094

management:
    endpoint:
        hystrix:
            stream:
                enabled: false
        health:
            show-details: always
    endpoints:
        web:
            cors:
                allowed-origins: "*"
            exposure:
                include: "*"
                #                include: "hystrix.stream"
                exclude: threaddump, heapdump

spring:
    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8880/auth/realms/spring-cloud-microservices-realm

    logstash:
        server: ${LOGSTASH_SERVER:localhost}
        port: ${LOGSTASH_PORT:5000}
