eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
    port: 8094

management:
    endpoint:
        hystrix:
            stream:
                enabled: true
        health:
            show-details: always
    endpoints:
        web:
            cors:
                allowed-origins: "*"
            exposure:
                include: "*"
                #                include: "hystrix.stream"
                exclude: threaddump, heapdump


spring:
    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

# App Properties
department-service:
    cors:
        allowed-origins: "http://localhost:8080"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
