eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    ### Configures the application's credentials as metadata in Eureka so that the
    ### Spring Boot Admin will be able to authenticate against Actuator security.
    instance:
        metadata-map:
            user.name: ${employee-service.security.username}
            user.password: ${employee-service.security.password}

server:
    port: 8092

management:
    endpoint:
        hystrix:
            stream:
                enabled: true
        health:
            show-details: always
    endpoints:
        web:
            cors:
                allowed-origins: "*"
            exposure:
                include: "*"
                #                include: "hystrix.stream"
                exclude: threaddump, heapdump

spring:
    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

# App Properties
employee-service:
    security:
        username: admin
        password: password
        role: ADMIN
        authorities: ROLE_ADMIN
    cors:
        allowed-origins: "http://localhost:8080"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
