eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
    port: 8092

management:
    endpoint:
        hystrix:
            stream:
                enabled: false
        health:
            show-details: always
    endpoints:
        web:
            cors:
                allowed-origins: "*"
            exposure:
                include: "*"
                #                include: "hystrix.stream"
                exclude: threaddump, heapdump

spring:
    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8880/auth/realms/spring-cloud-microservices-realm

    logstash:
        server: ${LOGSTASH_SERVER:localhost}
        port: ${LOGSTASH_PORT:5000}

    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}

    cloud:
        bus:
            id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
            enabled: true
            refresh:
                enabled: true
            env:
                enabled: true

# App Properties
employee-service:
    cors:
        allowed-origins: "http://localhost:8080,http://localhost:3000"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
