spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
#            default-filters:
#                -   name: GlobalFilter
#                    args:
#                        baseMessage: Spring Cloud Gateway GlobalFilter
#                        preLogger: true
#                        postLogger: true
            routes:
                -   id: employee-service
                    uri: lb://employee-service
                    predicates:
                        - Path=/employee/**
                    filters:
                        - RewritePath=/employee/(?<path>.*), /$\{path}
                -   id: department-service
                    uri: lb://department-service
                    predicates:
                        - Path=/department/**
                    filters:
                        - RewritePath=/department/(?<path>.*), /$\{path}
                -   id: organization-service
                    uri: lb://organization-service
                    predicates:
                        - Path=/organization/**
                    filters:
                        - RewritePath=/organization/(?<path>.*), /$\{path}

                -   id: openapi
                    uri: http://localhost:${server.port}
                    predicates:
                        - Path=/v3/api-docs/**
                    filters:
                        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
    swagger-ui:
        urls:
            - name: employee
              url: /v3/api-docs/employee
            - name: department
              url: /v3/api-docs/department
            - name: organization
              url: /v3/api-docs/organization

    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

ribbon:
    eureka:
        enabled: true

server:
    port: 8080
