spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
            routes:
                -   id: microservice
                    uri: lb://microservice
                    predicates:
                        - Path=/hello/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8080
