eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
### Configures the application's credentials as metadata in Eureka so that the
### Spring Boot Admin will be able to authenticate against Actuator security.
    instance:
        metadata-map:
            user.name: admin
            user.password: password
server:
    port: 8090

management:
    endpoint:
        hystrix:
            stream:
                enabled: true
        health:
            show-details: always
    endpoints:
        web:
            cors:
                allowed-origins: "*"
            exposure:
                include: "*"
#                include: "hystrix.stream"
                exclude: threaddump, heapdump

spring:
    # Zipkin info
    zipkin:
        base-url: http://localhost:9411/
    sleuth:
        sampler:
            probability: 1

springdoc:
    swagger-ui:
        enabled: true
        path: '/openapi/ui/index.html'
    api-docs:
        path: '/api/v3/api-docs'
        enabled: true

# App Properties
springcloudexamples:
    cors:
        allowed-origins: "http://localhost:8080"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        allow-credentials: true
        max-age: 1800
