application:
    title: config-server
    version: 0.0.1
spring:
    application:
        name: config-server
    cloud:
        bus:
            id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
            enabled: true
        config:
            server:
#                git:
#                    uri: https://github.com/tareqmy/cloudconfigrepo
#                    search-paths: configs
#                    clone-on-start: true
#  native mode cane applied with the following commented section
                native:
                    search-locations: classpath:/configurations
    profiles:
        active: native

    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}

server:
    port: 8888

# Logging
logging:
    level:
        root: INFO
        #        web: DEBUG
        com.tareqmy.configserver: DEBUG
