spring:
    cloud:
        config:
            server:
                git:
#                    uri: https://github.com/habuma/tacocloud-config
                    uri: https://github.com/tareqmy/cloudconfigrepo
                    search-paths: configs
server:
    port: 8888
