application:
    title: config-server
    version: 0.0.1
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
#  the following git repo can be used from locally and only needs commit. no push required
#                    uri: ${HOME}/development/projects/spring/cloudconfigrepo
##                    uri: https://github.com/tareqmy/cloudconfigrepo
#                    search-paths: configs
#                    clone-on-start: true
#  native mode can be applied with the following commented section
                native:
                    search-locations: classpath:/configurations
    profiles:
        active: native

server:
    port: 8888

# Logging
logging:
    level:
        root: INFO
        #        web: DEBUG
        com.tareqmy.configserver: DEBUG
